
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyumytbxmbgveowhzhec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5dW15dGJ4bWJndmVvd2h6aGVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NjA4MzMsImV4cCI6MjA1OTIzNjgzM30.uQMu9S9mm_eGVHC-_LVTG8kqOnwIg01OxEXXc2bGkms";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
